/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taxservice;

import java.io.IOException;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/servlet")
public class TaxService extends HttpServlet {

    @PersistenceContext(unitName = "TaxService")
    EntityManager em;

    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        System.out.println("bloody works right");
        TypedQuery<Tax> query = em.createQuery("SELECT t FROM Tax t WHERE t.destination = :country AND t.good = :good", Tax.class);
        System.out.println("created query");
        Country country = new Country();
        country.setName("England");
        query.setParameter("country", country);
        query.setParameter("good", "Zigaretten");
        Tax res2 = query.getSingleResult();
        System.out.println("tax-query-result: " + res);
    }
}
